---
# tasks file for ansible-roundcube
- name: PHP | Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  args:
    warn: no
  when: roundcube_install_composer | bool

- name: extract roundcube package
  unarchive:
    src: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz"
    dest: /tmp
    remote_src: yes

- name: clean directory installer
  file:
    state: absent
    path: "/tmp/roundcubemail-{{ roundcube_version }}/installer"

- name: create directory htdocs
  file:
    path: "{{ roundcube_htdocs }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: copy source to htdocs
  shell: 'cp -r /tmp/roundcubemail-{{ roundcube_version }}/. {{ roundcube_htdocs }}'

- name: Change permissions
  file:
    path: "{{ roundcube_htdocs }}/{{ item }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  with_items:
    - logs
    - temp

- name: set config.inc.php file
  template:
    src: config.inc.php.j2
    dest: "{{ roundcube_htdocs }}/config/config.inc.php"

- name: import database schema.sql
  mysql_db:
    name: "{{ roundcube_db_name }}"
    login_user: "{{ roundcube_db_user }}"
    login_password: "{{ roundcube_db_password }}"
    state: import
    target: "/tmp/roundcubemail-{{ roundcube_version }}/SQL/mysql.initial.sql"
